CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL
);

CREATE TABLE games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    goal VARCHAR (255) NOT NULL,
    start_time TIMESTAMP DEFAULT now() NOT NULL,
    end_time TIMESTAMP NULL,
    status INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE template_modules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR (30) NOT NULL,
    description VARCHAR (255) NOT NULL,
    sort_order INTEGER DEFAULT 1 NOT NULL
);

CREATE TABLE game_modules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id INTEGER REFERENCES games(id) ON DELETE CASCADE NOT NULL,
    template_modules_id INTEGER REFERENCES template_modules(id) ON DELETE CASCADE NOT NULL,
    notes VARCHAR (255) NULL,
    status INTEGER DEFAULT 0 NOT NULL
);


-- INSERT INTO public.users (user_name,"password") VALUES 
-- ('admin','admin')
-- ,('user','user')
-- ,('log','log')
-- ,('sandra','sandra')
-- ;

-- INSERT INTO public.book_collection (user_id,collection_name) VALUES 
-- (4,'Romance')
-- ,(2,'Science and Robots')
-- ,(1,'Healthcare')
-- ,(3,'Sea Animals')
-- ;
